name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Ensure that ID token write permission is enabled
      contents: read   # Grant read access to the repository contents if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build steps here...

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # Add any required inputs here
